on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 17 * * *'
name: Mirror GitHub Auto Queried Repos to Gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/lhztop
        dst: gitee/lhztop
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        mappings: ".github=>github"
        force_update: true
