on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: repo-sync
        uses: lhztop/sync-upstream-repo@master
        with:
          source_repo: 'lhztop/LLaVA lhztop/ComfyUI'
          source_branch: 'main'
          github_token: ${{ secrets.PAT }}
